/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ResellerIndexRouteImport } from './routes/reseller/index'
import { Route as ResellerLoginRouteImport } from './routes/reseller/login'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerIndexRoute = ResellerIndexRouteImport.update({
  id: '/reseller/',
  path: '/reseller/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerLoginRoute = ResellerLoginRouteImport.update({
  id: '/reseller/login',
  path: '/reseller/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download-app': typeof DownloadAppRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/admin/login': typeof AdminLoginRoute
  '/reseller/login': typeof ResellerLoginRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/reseller/': typeof ResellerIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download-app': typeof DownloadAppRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/admin/login': typeof AdminLoginRoute
  '/reseller/login': typeof ResellerLoginRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/reseller': typeof ResellerIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download-app': typeof DownloadAppRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/admin/login': typeof AdminLoginRoute
  '/reseller/login': typeof ResellerLoginRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/reseller/': typeof ResellerIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download-app'
    | '/history'
    | '/landing'
    | '/notifications'
    | '/payment-success'
    | '/privacy-policy'
    | '/profile'
    | '/providers'
    | '/admin/login'
    | '/reseller/login'
    | '/superadmin/login'
    | '/admin/'
    | '/reseller/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download-app'
    | '/history'
    | '/landing'
    | '/notifications'
    | '/payment-success'
    | '/privacy-policy'
    | '/profile'
    | '/providers'
    | '/admin/login'
    | '/reseller/login'
    | '/superadmin/login'
    | '/admin'
    | '/reseller'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/download-app'
    | '/history'
    | '/landing'
    | '/notifications'
    | '/payment-success'
    | '/privacy-policy'
    | '/profile'
    | '/providers'
    | '/admin/login'
    | '/reseller/login'
    | '/superadmin/login'
    | '/admin/'
    | '/reseller/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadAppRoute: typeof DownloadAppRoute
  HistoryRoute: typeof HistoryRoute
  LandingRoute: typeof LandingRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ResellerLoginRoute: typeof ResellerLoginRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ResellerIndexRoute: typeof ResellerIndexRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/': {
      id: '/reseller/'
      path: '/reseller'
      fullPath: '/reseller/'
      preLoaderRoute: typeof ResellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/login': {
      id: '/reseller/login'
      path: '/reseller/login'
      fullPath: '/reseller/login'
      preLoaderRoute: typeof ResellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadAppRoute: DownloadAppRoute,
  HistoryRoute: HistoryRoute,
  LandingRoute: LandingRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  AdminLoginRoute: AdminLoginRoute,
  ResellerLoginRoute: ResellerLoginRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ResellerIndexRoute: ResellerIndexRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
